import localFont from "next/font/local";
import "./globals.css";
import { Archivo, Archivo_Narrow } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const archivo = Archivo({
  subsets: ['latin'],
  variable: '--font-archivo',
})

const archivo_narrow = Archivo_Narrow({
  subsets: ['latin'],
  variable: '--font-archivo-narrow',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />
      </head>
      <body>
        <main className={`${archivo.variable} font-archivo overflow-x-hidden`}>
        {children}
        </main>
      </body>
    </html>
  );
}
